{
 "title": "ArgoWorkflow Metrics",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "ns",
    "label": "k8s_ns",
    "query": {
     "query": "label_values(argo_workflows_count,kubernetes_namespace) "
    }
   }
  ]
 },
 "panels": [
  { "title": "Currently", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 1 },
   "options": {
    "content": "<img src=\"https://argoproj.github.io/static/argo-wheel.23b3ad84.png\" />"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "WF Pending",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "argo_workflows_count{kubernetes_namespace=~\"$ns\",status=\"Pending\"} "
    }
   ]
  },
  {
   "title": "WF Running",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "argo_workflows_count{kubernetes_namespace=~\"$ns\",status=\"Running\"}"
    }
   ]
  },
  {
   "title": "WF Errors",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "argo_workflows_count{kubernetes_namespace=~\"$ns\",status=\"Error\"}"
    }
   ]
  },
  {
   "title": "WF Failed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "argo_workflows_count{kubernetes_namespace=~\"$ns\",status=\"Failed\"}"
    }
   ]
  },
  {
   "title": "WF Skipped",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "argo_workflows_count{kubernetes_namespace=~\"$ns\",status=\"Skipped\"}"
    }
   ]
  },
  {
   "title": "WF Succeeded",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "argo_workflows_count{kubernetes_namespace=~\"$ns\",status=\"Succeeded\"}"
    }
   ]
  },
  {
   "title": "Number of Workflows currently accessible by the controller by status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 }
  },
  {
   "title": "Workflow Status  ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "argo_workflows_count{status!~\"(Error|Failed)\",kubernetes_namespace=~\"$ns\"}",
     "legendFormat": "{{app}} : {{kubernetes_namespace}} : {{status}}"
    }
   ]
  },
  {
   "title": "Workflow Errors Alerting ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "argo_workflows_count{status=~\"(Error|Failed)\"}",
     "legendFormat": "{{app}} : {{kubernetes_namespace}} : {{status}}"
    }
   ]
  },
  {
   "title": "Histogram of durations of operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 }
  },
  {
   "title": "Workflow operation duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(argo_workflows_operation_duration_seconds_bucket{kubernetes_namespace=~\"^$ns$\"}[5m])) by (le)) ",
     "legendFormat": "95th percentile"
    }
   ]
  },
  { "title": "Adds to the queue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Workflow queue adds ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(argo_workflows_queue_adds_count{kubernetes_namespace=~\"$ns\"}[2m])",
     "legendFormat": "{{app}} : {{kubernetes_namespace}} : {{queue_name}}"
    }
   ]
  },
  {
   "title": "Depth of the queue",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "argo_workflows_queue_depth_count{kubernetes_namespace=~\"$ns\"}",
     "legendFormat": "{{app}} : {{kubernetes_namespace}} : {{queue_name}}"
    }
   ]
  },
  {
   "title": "Time objects spend waiting in the queue",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "s", "label": "avg" }
   ],
   "targets": [
    {
     "expr": "  rate(argo_workflows_queue_latency_sum{queue_name=\"cron_wf_queue\",kubernetes_namespace=~\"^$ns$\"}[5m])\n/\n  rate(argo_workflows_queue_latency_count{queue_name=\"cron_wf_queue\",kubernetes_namespace=~\"^$ns$\"}[5m])",
     "legendFormat": "{{app}} : {{kubernetes_namespace}} : {{queue_name}}"
    },
    {
     "expr": "  rate(argo_workflows_queue_latency_sum{queue_name=\"pod_queue\",kubernetes_namespace=~\"^$ns$\"}[5m])\n/\n  rate(argo_workflows_queue_latency_count{queue_name=\"pod_queue\",kubernetes_namespace=~\"^$ns$\"}[5m])",
     "legendFormat": "{{app}} : {{kubernetes_namespace}} : {{queue_name}}"
    },
    {
     "expr": "  rate(argo_workflows_queue_latency_sum{queue_name=\"wf_cron_queue\",kubernetes_namespace=~\"^$ns$\"}[5m])\n/\n  rate(argo_workflows_queue_latency_count{queue_name=\"wf_cron_queue\",kubernetes_namespace=~\"^$ns$\"}[5m])",
     "legendFormat": "{{app}} : {{kubernetes_namespace}} : {{queue_name}}"
    },
    {
     "expr": "  rate(argo_workflows_queue_latency_sum{queue_name=\"workflow_queue\",kubernetes_namespace=~\"^$ns$\"}[5m])\n/\n  rate(argo_workflows_queue_latency_count{queue_name=\"workflow_queue\",kubernetes_namespace=~\"^$ns$\"}[5m])",
     "legendFormat": "{{app}} : {{kubernetes_namespace}} : {{queue_name}}"
    }
   ]
  },
  { "title": "Total number of log messages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Log messages",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short", "label": "count/sec" }
   ],
   "targets": [
    {
     "expr": "rate(log_messages{kubernetes_namespace=~\"$ns\"}[2m])",
     "legendFormat": "{{app}} : {{kubernetes_namespace}} : {{level}}"
    }
   ]
  }
 ]
}
{
 "title": "Spark: Applications",
 "description": "Spark Executors and Driver Level Metrics with filtering by service",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "K8s Namespace",
    "query": {
     "query": "label_values(kube_pod_labels{label_sparkoperator_k8s_io_launched_by_spark_operator=\"true\"}, namespace)"
    }
   },
   {
    "name": "app_name",
    "label": "Application Name",
    "query": {
     "query": "label_values(kube_pod_labels{namespace = \"$namespace\"}, label_sparkoperator_k8s_io_app_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "% of nodes utilized",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(kube_pod_info and on(pod) (kube_pod_status_phase{phase=\"Running\"} == 1) and on(pod) (kube_pod_labels{label_spark_role=\"executor\"})) by (node)) / count(kube_node_labels and on(pod) (kube_pod_status_phase{phase=\"Running\"} == 1))"
    }
   ]
  },
  {
   "title": "CPU utilization %",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 5, "x": 5, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(\n    (sum(rate(container_cpu_usage_seconds_total{}[1m])) by (pod, namespace))\n    and on(pod) kube_pod_labels{label_spark_role=\"executor\"} \n    and on(pod) (kube_pod_status_phase{phase=\"Running\"} == 1)))\n/ \n(sum(\n    (sum(kube_pod_container_resource_requests{resource=\"cpu\"}) by (pod, namespace))\n    and on(pod) kube_pod_labels{label_spark_role=\"executor\"} \n    and on(pod) (kube_pod_status_phase{phase=\"Running\"} == 1)))"
    }
   ]
  },
  {
   "title": "Memory utilization %",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 5, "x": 10, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(\n   (sum(container_memory_working_set_bytes{}) by (pod, namespace))\n   and on(pod) kube_pod_labels{label_spark_role=\"executor\"} \n   and on(pod) (kube_pod_status_phase{phase=\"Running\"} == 1))\n/ \nsum(\n   (sum(kube_pod_container_resource_requests{resource=\"memory\"}) by (pod, namespace))\n   and on(pod) kube_pod_labels{label_spark_role=\"executor\"} \n   and on(pod) (kube_pod_status_phase{phase=\"Running\"} == 1))"
    }
   ]
  },
  {
   "title": "Drivers Running",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 3, "x": 15, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_labels{label_spark_role=\"driver\",label_sparkoperator_k8s_io_app_name=~\"$app_name\"})"
    }
   ]
  },
  {
   "title": "Executors Running",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 3, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_labels{label_spark_role=\"executor\",label_sparkoperator_k8s_io_app_name=~\"$app_name\"})"
    }
   ]
  },
  { "title": "Namespace Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Network I/O pressure",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "(sum(\n    (sum(rate(container_network_receive_bytes_total{}[1m])) by (pod, namespace))\n    and on(pod) kube_pod_labels{label_spark_role=\"executor\"} \n    and on(pod) (kube_pod_status_phase{phase=\"Running\"} == 1))\nby (namespace))",
     "legendFormat": "IN {{ namespace }}"
    },
    {
     "expr": "- (sum(\n    (sum(rate(container_network_transmit_bytes_total{}[1m])) by (pod, namespace))\n    and on(pod) kube_pod_labels{label_spark_role=\"executor\"} \n    and on(pod) (kube_pod_status_phase{phase=\"Running\"} == 1))\nby (namespace))",
     "legendFormat": "OUT {{ namespace }}"
    }
   ]
  },
  {
   "title": "Memory utilization %",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 7, "y": 11 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(sum(\n    (sum(container_memory_working_set_bytes{}) by (pod, namespace))\n    and on(pod) kube_pod_labels{label_spark_role=\"executor\"} \n    and on(pod) (kube_pod_status_phase{phase=\"Running\"} == 1))\nby (namespace) /1024 / 1024 / 1024) \n/ \n(sum(\n    (sum(kube_pod_container_resource_requests{resource=\"memory\"}) by (pod, namespace))\n    and on(pod) kube_pod_labels{label_spark_role=\"executor\"} \n    and on(pod) (kube_pod_status_phase{phase=\"Running\"} == 1)) \nby (namespace) / 1024 / 1024 / 1024)",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "CPU utilization %",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 14, "y": 11 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(sum(\n    (sum(rate(container_cpu_usage_seconds_total{}[1m])) by (pod, namespace))\n    and on(pod) kube_pod_labels{label_spark_role=\"executor\"} \n    and on(pod) (kube_pod_status_phase{phase=\"Running\"} == 1))\nby (namespace))\n/ \n(sum(\n    (sum(kube_pod_container_resource_requests{resource=\"cpu\"}) by (pod, namespace))\n    and on(pod) kube_pod_labels{label_spark_role=\"executor\"} \n    and on(pod) (kube_pod_status_phase{phase=\"Running\"} == 1))\nby (namespace))",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  { "title": "Cluster Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "CPUs Used",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\", container=\"spark-kubernetes-driver\", pod=~\"($app_name).*\", resource=\"cpu\"}) by (namespace)",
     "legendFormat": "CPUs Used by Driver"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\", container=\"spark-kubernetes-executor\", pod=~\"($app_name).*\", resource=\"cpu\"}) by (namespace)",
     "legendFormat": "CPUs Used by Executor"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\", pod=~\"($app_name).*\", resource=\"cpu\"}) by (namespace)",
     "legendFormat": "Total CPUs Used"
    }
   ]
  },
  {
   "title": "Mem Used",
   "type": "graph",
   "gridPos": { "h": 10, "w": 11, "x": 10, "y": 22 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\", container=\"spark-kubernetes-driver\", pod=~\"($app_name).*\", resource=\"memory\"}) by (namespace)",
     "legendFormat": "Mem Used by Driver"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\", container=\"spark-kubernetes-executor\", pod=~\"($app_name).*\", resource=\"memory\"}) by (namespace)",
     "legendFormat": "Mem Used by Executors"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\", pod=~\"($app_name).*\", resource=\"memory\"}) by (namespace)",
     "legendFormat": "Total Mem Used"
    }
   ]
  },
  { "title": "Execution Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Executor Non-Heap Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "Sum(metrics_executor_JVMOffHeapMemory_bytes{namespace=~\"$namespace\",application_name=~\"$app_name\"} ) by (application_id)",
     "legendFormat": "{{application_id}}"
    }
   ]
  },
  {
   "title": "Executor Heap Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 7, "y": 33 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(metrics_executor_JVMHeapMemory_bytes{namespace=~\"$namespace\",application_name=~\"$app_name\"}) by (application_id) ",
     "legendFormat": "{{application_id}}"
    }
   ]
  },
  {
   "title": "Tasks",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 14, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SUM(metrics_executor_activeTasks{namespace=~\"$namespace\", application_name=~\"$app_name\"})",
     "legendFormat": "Active tasks"
    },
    {
     "expr": "SUM(metrics_executor_totalTasks_total{namespace=\"$namespace\", application_name=~\"$app_name\"})",
     "legendFormat": "Total tasks"
    },
    {
     "expr": "SUM(metrics_executor_failedTasks_total{namespace=\"$namespace\", application_name=~\"$app_name\"})",
     "legendFormat": "Failed Tasks"
    }
   ]
  },
  {
   "title": "Driver Network I/O",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=~\"$namespace\", pod=~\"($app_name).*\"}[2m])) by (pod_name)",
     "legendFormat": "{{ pod_name }}  Received"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"($app_name).*\"}[2m])) by (pod_name)",
     "legendFormat": "{{ pod_name }}  Transmitted"
    }
   ]
  },
  {
   "title": "Major Garbage Collection",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(metrics_executor_MajorGCTime_seconds_total{namespace=~\"$namespace\", application_name=~\"$app_name\"}) by (application_id)",
     "legendFormat": "{{application_id}}"
    }
   ]
  },
  {
   "title": "Shuffle",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 42 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "SUM(metrics_executor_totalShuffleWrite_bytes_total{namespace=~\"$namespace\", application_name=~\"$app_name\"})",
     "legendFormat": "Shuffle Write"
    },
    {
     "expr": "SUM(metrics_executor_totalShuffleRead_bytes_total{namespace=~\"$namespace\", application_name=~\"$app_name\"})",
     "legendFormat": "Shuffle Read"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum({__name__=~\"metrics_spark_.*_driver_spark_streaming_.*_latency_Value\"}) by (name)",
     "legendFormat": "Spark Streaming Latency"
    }
   ]
  },
  {
   "title": "Rates",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 9, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum({__name__=~\"metrics_spark_.*_driver_spark_streaming_.*_processingRate_total_Value\"}) by (name) ",
     "legendFormat": "Processing Rate"
    },
    {
     "expr": " sum({__name__=~\"metrics_spark_.*_driver_spark_streaming_.*_inputRate_total_Value\"}) by (name)",
     "legendFormat": "Input Rate"
    }
   ]
  },
  {
   "title": "Watermark",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum({__name__=~\"metrics_spark_.*_driver_spark_streaming_.*_eventTime_watermark_Value\"}) by (name) ",
     "legendFormat": "Watermark"
    }
   ]
  },
  {
   "title": "Rows Processed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 9, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum({__name__=~\"metrics_spark_.*_driver_spark_streaming_.*_states_rowsTotal_Value\"}) by (name) ",
     "legendFormat": "Total Rows"
    }
   ]
  }
 ]
}